INSERT INTO `rutass`(`origen`, `destino`) VALUES ('6','1');
INSERT INTO `rutass`(`origen`, `destino`) VALUES ('','');
INSERT INTO `rutass`(`origen`, `destino`) VALUES ('','');

INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('ALBANIA','DESTINO','ALB');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('APURE','DESTINO','AP');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('ARACATACA','DESTINO','ARC');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('ARJONA','DESTINO','ARJ');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('BARRANCAS','DESTINO','BARR');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('BARRANQUILLA','DESTINO','BQILLA');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('BECERRIL','DESTINO','B');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('BOSCONIA','DESTINO','BOS');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('CHIMICHAGUA','DESTINO','CHIM');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('CHIRIGUANA','DESTINO','CHIR');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('CIENAGA','DESTINO','CIE');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('CODAZZI','DESTINO','C');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('CRUCE CHIRIGUANA','DESTINO','CR');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('CUATRO VIENTOS','DESTINO','CV');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('CUESTECITA','DESTINO','CUE');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('CURUMANI','DESTINO','CUR');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('EL BANCO','DESTINO','EBAN');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('EL BURRO','DESTINO','EBURR');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('EL COPEY','DESTINO','EC');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('EL DIFICIL','DESTINO','ED');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('EL PASO','DESTINO','EP');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('FONSECA','DESTINO','F');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('FUNDACION','DESTINO','FUND');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('GRANADA','DESTINO','GR');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('HATO NUEVO','DESTINO','HN');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('LA GLORIA','DESTINO','LGLO');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('LA JAGUA DE IBIRICO','DESTINO','LJDI');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('LA LOMA DEL BALSAMO','DESTINO','LLDB');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('MAICAO','DESTINO','M');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('MANDINGUILLA','DESTINO','MAND');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('MARIA ANGOLA','DESTINO','MA');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('PAILITAS','DESTINO','PAI');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('PLATO','DESTINO','PLA');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('PUEBLO NUEVO','DESTINO','PN');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('RINCON HONDO','DESTINO','RHON');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('RIO HACHA','DESTINO','RHA');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('SAN JUAN','DESTINO','SJ');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('SAN ROQUE','DESTINO','SR');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('SANTA MARTA','DESTINO','SM');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('TAMALAMEQUE','DESTINO','T');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('VALLEDUPAR','DESTINO','V');
INSERT INTO `lugares`(`nombre`, `tipo`, `avLugar`) VALUES ('VILLA NUEVA','DESTINO','VN');